#!/bin/bash
# Include Beaker environment
. /usr/bin/rhts-environment.sh || exit 1
. /usr/share/beakerlib/beakerlib.sh || exit 1

PACKAGE="ext4-task"

rlJournalStart

    rlPhaseStartTest
        rlRun "cat /proc/filesystems | grep 'sysfs'" 0 "Check if sysfs is supported"
    rlPhaseEnd

    rlJournalPrintText
rlJournalEnd
